- name: Baseline router setup
  hosts: router
  gather_facts: no
  tasks:
    - name: Set hostname and domain
      cisco.ios.ios_config:
        lines:
          - hostname HomeRouter
          - ip domain-name home.lab

    - name: Create management user
      cisco.ios.ios_config:
        lines:
          - username admin privilege 15 secret MySecurePass

    - name: Enable SSH
      cisco.ios.ios_config:
        lines:
          - crypto key generate rsa modulus 2048
          - ip ssh version 2
          - line vty 0 4
          - transport input ssh
